CRON_EXAMPLES = [
    {"expression": "0 9 * * *", "description": "Daily at 9:00 AM"},
    {"expression": "0 9 * * 1-5", "description": "Weekdays at 9:00 AM"},
    {"expression": "0 9 * * 1", "description": "Mondays at 9:00 AM"},
    {"expression": "30 8 * * *", "description": "Daily at 8:30 AM"},
    {"expression": "0 0 1 * *", "description": "First day of month at midnight"},
    {"expression": "0 12 * * *", "description": "Daily at noon"},
    {"expression": "0 18 * * 5", "description": "Fridays at 6:00 PM"},
    {"expression": "*/15 * * * *", "description": "Every 15 minutes"},
    {"expression": "0 */2 * * *", "description": "Every 2 hours"},
    {"expression": "0 9,17 * * *", "description": "At 9 AM and 5 PM daily"},
]

TIMEZONES = [
    {"zone": "UTC", "region": "Universal"},
    {"zone": "America/New_York", "region": "Americas"},
    {"zone": "America/Chicago", "region": "Americas"},
    {"zone": "America/Denver", "region": "Americas"},
    {"zone": "America/Los_Angeles", "region": "Americas"},
    {"zone": "America/Sao_Paulo", "region": "Americas"},
    {"zone": "Europe/London", "region": "Europe"},
    {"zone": "Europe/Paris", "region": "Europe"},
    {"zone": "Europe/Berlin", "region": "Europe"},
    {"zone": "Europe/Warsaw", "region": "Europe"},
    {"zone": "Europe/Moscow", "region": "Europe"},
    {"zone": "Asia/Dubai", "region": "Asia"},
    {"zone": "Asia/Kolkata", "region": "Asia"},
    {"zone": "Asia/Singapore", "region": "Asia"},
    {"zone": "Asia/Tokyo", "region": "Asia"},
    {"zone": "Asia/Shanghai", "region": "Asia"},
    {"zone": "Asia/Seoul", "region": "Asia"},
    {"zone": "Australia/Sydney", "region": "Oceania"},
    {"zone": "Australia/Melbourne", "region": "Oceania"},
    {"zone": "Pacific/Auckland", "region": "Oceania"},
    {"zone": "Africa/Cairo", "region": "Africa"},
    {"zone": "Africa/Johannesburg", "region": "Africa"},
]
